/**
 * x86 -> WASM JIT engine (design doc 4.1.5/4.1.6/4.1.7).
 *
 * Each compiled basic block becomes a real WASM function that reads/writes the
 * guest CPU state in the shared linear memory and returns a BlockStatus. The
 * engine caches compiled blocks by address, tracks JIT statistics, and turns
 * unsupported opcodes into faulting blocks that the dispatcher reports.
 */

import type { BasicBlock, CompiledBlock, JitEngine, JitStats, WasmRuntime } from '@bk/contracts';
import { X86Decoder, UnsupportedError } from './x86-decoder';
import { buildBlockFunction } from './codegen';
import { WasmModuleBuilder } from './wasm-encoder';
import { STATUS_FAULT } from './cpu';

export class IncompleteBlockError extends Error {
  constructor(public readonly address: number) {
    super(`block at 0x${address.toString(16)} is incomplete (needs more code bytes)`);
    this.name = 'IncompleteBlockError';
  }
}

export class JitEngineImpl implements JitEngine {
  readonly supportedFeatures = ['x86-32', 'x86-64', 'wasm-jit:1'] as const;

  private readonly decoder: X86Decoder;
  private readonly cache = new Map<number, CompiledBlock>();
  private stats: JitStats = {
    cacheHits: 0,
    cacheMisses: 0,
    cacheBytes: 0,
    compiledBlocks: 0,
    totalCompileMs: 0,
  };

  constructor(
    private readonly runtime: WasmRuntime,
    private readonly mode: 'x86' | 'x64' = 'x86',
  ) {
    this.decoder = new X86Decoder(mode);
  }

  async compile(block: BasicBlock): Promise<CompiledBlock> {
    const cached = this.cache.get(block.startAddress);
    if (cached) {
      this.stats.cacheHits += 1;
      return cached;
    }
    this.stats.cacheMisses += 1;

    if (block.code.byteLength === 0) {
      throw new IncompleteBlockError(block.startAddress);
    }

    const start = performance.now();
    let compiled: CompiledBlock;
    try {
      compiled = this.compileBlock(block);
    } catch (err) {
      if (err instanceof UnsupportedError) {
        compiled = this.faultBlock(block.startAddress);
      } else {
        throw err;
      }
    }
    this.stats.compiledBlocks += 1;
    this.stats.cacheBytes += block.code.byteLength;
    this.stats.totalCompileMs += performance.now() - start;
    this.cache.set(block.startAddress, compiled);
    return compiled;
  }

  invalidate(startAddress: number): void {
    this.cache.delete(startAddress);
  }

  clearCache(): void {
    this.cache.clear();
    this.stats.cacheHits = 0;
    this.stats.cacheMisses = 0;
    this.stats.cacheBytes = 0;
    this.stats.compiledBlocks = 0;
    this.stats.totalCompileMs = 0;
  }

  getStats(): JitStats {
    return { ...this.stats };
  }

  // -------------------------------------------------------------------------

  private compileBlock(block: BasicBlock): CompiledBlock {
    const decoded = this.decoder.decode(block.code, block.startAddress);
    const fn = buildBlockFunction(decoded.instructions, { terminated: decoded.terminated, endAddress: decoded.endAddress, mode: this.mode });

    const builder = new WasmModuleBuilder();
    const typeIdx = builder.addType([], ['i32']);
    builder.addMemoryImport('env', 'memory', 1);
    builder.defineFunction(typeIdx, fn);
    builder.exportFunction('run', 0);
    return this.instantiate(builder, fn, block.startAddress, decoded.length);
  }

  private faultBlock(address: number): CompiledBlock {
    const builder = new WasmModuleBuilder();
    const typeIdx = builder.addType([], ['i32']);
    builder.addMemoryImport('env', 'memory', 1);
    const fn = builder.defineFunction(typeIdx);
    fn.i32Const(STATUS_FAULT);
    fn.return_();
    fn.end();
    builder.exportFunction('run', 0);
    return this.instantiate(builder, fn, address, 1);
  }

  private instantiate(builder: WasmModuleBuilder, fn: import('./wasm-encoder').WasmFunction, address: number, size: number): CompiledBlock {
    const bytes = builder.build();
    let module: WebAssembly.Module;
    let instance: WebAssembly.Instance;
    try {
      module = new WebAssembly.Module(bytes as unknown as ArrayBuffer);
      instance = new WebAssembly.Instance(module, { env: { memory: this.runtime.memory } });
    } catch (err) {
      // Surface validation errors with the generated bytes for debugging.
      throw new Error(`JIT wasm validation failed at 0x${address.toString(16)}: ${String(err)}`);
    }
    const run = instance.exports.run as () => number;
    return { address, entry: () => run(), size };
  }
}
